- name: Deploy Apache Web Server in Podman Container
  hosts: all
  remote_user: azureuser
  become: true
  vars:
    container_name: apache_container
    container_image: fedora
    httpasswd_user: myuser
    httpasswd_password: mypassword
  tasks:
  - name: Install Podman and Apache Web Server
    dnf:
      name:
        - podman
        - httpd
      state: latest

  - name: Create Podman Container
    containers.podman.podman_image:
      name: "{{ container_name }}"
      image: "{{ container_image }}"
      state: started
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - "/var/www/html:/var/www/html"
        - "/etc/pki/tls/certs:/etc/pki/tls/certs"
        - "/etc/pki/tls/private:/etc/pki/tls/private"
      env:
        - "LANG=en_US.UTF-8"
      tty: true

  - name: Generate SSL Certificate
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/tls/private/server.key -out /etc/pki/tls/certs/server.crt -subj "/CN=example.com/O=My Company Name/L=My City/ST=My State/C=My Country"

  - name: Configure Apache Web Server
    copy:
      dest: /etc/httpd/conf.d/ssl.conf
      content: |
        LoadModule ssl_module modules/mod_ssl.so
        Listen 443 https
        <VirtualHost *:443>
          ServerName example.com
          DocumentRoot /var/www/html
          SSLEngine on
          SSLCertificateFile /etc/pki/tls/certs/server.crt
          SSLCertificateKeyFile /etc/pki/tls/private/server.key
        </VirtualHost>
      validate: /usr/sbin/apachectl -t
    notify:
      - restart httpd

  - name: Add Basic Auth
    command: htpasswd -bc /etc/httpd/.htpasswd "{{ httpasswd_user }}" "{{ httpasswd_password }}"

  - name: Create Web Page
    copy:
      dest: /var/www/html/index.html
      content: |
        <html>
        <head>
          <title>Hello World</title>
        </head>
        <body>
          <h1>Hello World</h1>
        </body>
        </html>

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
