- name: Deploy Apache Web Server in Podman container
  hosts: all
  remote_user: azureuser
  vars:
    webroot: "/webroot"

  tasks:
  - name: Install Podman
    become: true
    dnf:
      name: podman
      state: present

  - name: Pull Fedora image
    become: true
    podman_image:
      name: fedora:latest
      pull: true

  - name: webroot present
    ansible.builtin.file:
      path: "{{ webroot }}"
      state: directory
      owner: "root"
      group: "root"
      mode: '0777'
      setype: "container_share_t"

  - name: custom index.html
    ansible.builtin.copy:
      dest: "{{ webroot }}/index.html"
      content: |
                  Custom Web Page
      setype: "container_share_t"

   - name: run httpd container
    containers.podman.podman_container:
      name: webserver
      image: httpd
      state: started
      detach: true
      expose:
        - 80
      ports:
        - 8080:80
      volume:
        - "{{ webroot }}:/usr/local/apache2/htdocs/:exec"

#  - name: Create Apache container
#    become: true
#    containers.podman.podman_container:
#      name: apache-webserver
#      image: fedora:latest
#      state: started
#      ports:
#        - 80:80
#      command: "/usr/sbin/httpd -DFOREGROUND"

#  - name: Create HTML directory and file
#    become: true
#    copy:
#      content: "HELLO WORLD"
#      dest: "/var/www/html/index.html"
#      dest: "/var/www/html"
#      state: directory
#      mode: '0755'

#  - name: Add data to file
#    copy:
#      content: "HELLO WORLD"
#      dest: "/var/www/html/index.html"

  - name: Generate x.509 self-signed certificate
    become: true
    openssl_certificate:
      path: /etc/pki/tls/certs/apache.crt
      privatekey_path: /etc/pki/tls/private/apache.key
      common_name: "localhost"
      type: "rsa"
      size: "2048"
      days: "365"
      state: present
      selfsigned: true

  - name: Install htpasswd
    become: true
    dnf:
      name: httpd-tools
      state: present

  - name: Create Apache basic authentication user
    become: true
    htpasswd:
      path: /etc/httpd/.htpasswd
      name: oruizmo
      password: "helloworld"

  - name: Configure Apache
    become: true
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
      mode: '0644'

  - name: Restart Apache
    become: true
    systemd:
      name: httpd
      state: restarted
