- name: Deploy Apache Web Server in Podman container
  hosts: all
  remote_user: azureuser
  vars:
    webroot: "/webroot"

  tasks:
  - name: Install Podman
    become: true
    dnf:
      name: podman
      state: present

  - name: Pull Fedora image
    become: true
    podman_image:
      name: fedora:latest
      pull: true

  - name: Crear webroot present
    become: true
    ansible.builtin.file:
      path: "{{ webroot }}"
      state: directory
      owner: "root"
      group: "root"
      mode: '0777'
      setype: "container_share_t"

  - name: Crear fichero index.html
    ansible.builtin.copy:
      dest: "{{ webroot }}/index.html"
      content: "<html><head>HOLA MUNDO</head><body>HOLA MUNDO, desplegado con Ansible</body></html>"
      setype: "container_share_t"

  - name: run httpd container
    containers.podman.podman_container:
      name: webserver
      image: httpd
      state: started
      detach: true
      expose:
        - 80
      ports:
        - 8080:80
      volume:
        - "{{ webroot }}:/usr/local/apache2/htdocs/:exec"

  - name: Generar directorio private key
    become: true
    ansible.builtin.file:
      path: "/etc/pki/tls/private"
      state: directory
      owner: "root"
      group: "root"
      mode: '0777'
      setype: "container_share_t"

  - name: Generate an OpenSSL private key
    become: true
    openssl_privatekey:
      path: /etc/pki/tls/private/apache.key
      size: "2048"
      type: "RSA"
      backup: yes

  - name: Generate x.509 self-signed certificate
    become: true
    openssl_certificate:
      path: /etc/pki/tls/certs/apache.crt
      privatekey_path: /etc/pki/tls/private/apache.key
#      common_name: "localhost"
#      type: "rsa"
#      size: "2048"
#      days: "365"
      state: present
      provider: selfsigned
#      selfsigned: true

  - name: Install htpasswd
    become: true
    dnf:
      name: httpd-tools
      state: present

  - name: Instalar libreria passlib
    pip: name=passlib
      
  - name: Create Apache basic authentication user
    become: true
    htpasswd:
      path: /etc/httpd/.htpasswd
      name: oruizmo
      password: "helloworld"

  - name: Configure Apache
    become: true
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
      mode: '0644'

  - name: Restart Apache
    become: true
    systemd:
      name: httpd
      state: restarted
