- name: Despliegue Servidor Web Apache en contenedor Podman
  hosts: all
  remote_user: azureuser
  vars:
    webroot: "/webroot"

  tasks:
  - name: Install Podman
    become: true
    dnf:
      name: podman
      state: present

  - name: Pull Fedora image
    become: true
    podman_image:
      name: fedora:latest
      pull: true

  - name: Create webroot 
    become: true
    ansible.builtin.file:
      path: "{{ webroot }}"
      state: directory
      owner: "root"
      group: "root"
      mode: '0777'
      setype: "container_share_t"

  - name: Create index.html file
    ansible.builtin.copy:
      dest: "{{ webroot }}/index.html"
      content: "<html><head>HOLA MUNDO</head><body>HOLA MUNDO, desplegado con Ansible</body></html>"
      setype: "container_share_t"

  - name: Run httpd container
    containers.podman.podman_container:
      name: webserver
      image: httpd
      state: started
      detach: true
      expose:
        - 80
      ports:
        - 8080:80
      volume:
        - "{{ webroot }}:/usr/local/apache2/htdocs/:exec"

  - name: Generate private key folder
    become: true
    ansible.builtin.file:
      path: "/etc/pki/tls/private"
      state: directory
      owner: "root"
      group: "root"
      mode: '0777'
      setype: "container_share_t"

  - name: Generate OpenSSL private key
    become: true
    openssl_privatekey:
      path: /etc/pki/tls/private/apache.key
      size: "2048"
      type: "RSA"
      backup: yes

  - name: Generate x.509 self-signed certificate
    become: true
    openssl_certificate:
      path: /etc/pki/tls/certs/apache.crt
      privatekey_path: /etc/pki/tls/private/apache.key
      state: present
      provider: selfsigned

  - name: Install htpasswd
    become: true
    dnf:
      name: httpd-tools
      state: present

  - name: Install passlib library
    become: true
    pip: 
      name: passlib
      
  - name: Create Apache basic authentication user
    become: true
    htpasswd:
      path: /etc/httpd/.htpasswd
      name: oruizmo
      password: "helloworld"

  - name: Generate Apache config folder
    become: true
    ansible.builtin.file:
      path: "/etc/httpd/conf"
      state: directory
      owner: "root"
      group: "root"
      mode: '0777'
      setype: "container_share_t"
      
  - name: Configure Apache
    become: true
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
      mode: '0644'

  - name: Restart Apache
    become: true
    systemd:
      state: restarted
      daemon_reload: true 
      name: webserver
